meson: Provide missing boost dependency and its wrap file
Currently local meson build fails with the error:
"""
fatal error: boost/asio/io_context.hpp: No such file or directory
"""
This is happening because boost is not listed as a dependency for the
targets that use it.
Add boost dependency for all the necessary targets and provide a wrap
file for boost for the local meson build.

Tested:
"meson setup build && cd build && meson compile" finishes successfully.

Change-Id: I3f418091d8a2da9377684e16ce3e2f88db4c6eb8
Signed-off-by: Konstantin Aladyshev <aladyshev22@gmail.com>